# Generated by Django 4.0 on 2022-02-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='bredPit.jpg', upload_to=''),
        ),
    ]
