# Generated by Django 4.0 on 2022-02-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_pcture',
            field=models.ImageField(default='book.png', upload_to=''),
        ),
    ]
